import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  loading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 50,
    paddingTop: 40,
    paddingBottom: 10,
  },
  wrapperImage: {
    width: 241,
    height: 241,
    paddingHorizontal: 100,
    justifyContent: 'center',
    borderRadius: 150,
    resizeMode: 'stretch',
    marginBottom: 50,
    marginTop: 30,
  },
  image: {
    width: 241,
    height: 241,
    borderRadius: 150,
  },
  content: {
    paddingHorizontal: 50,
  },
  productName: {
    fontFamily: 'Poppins-ExtraBold',
    fontSize: 28,
    lineHeight: 42,
    color: '#000',
    textAlign: 'center',
  },
  price: {
    fontFamily: 'Poppins-Bold',
    fontSize: 22,
    color: '#6A4029',
    textAlign: 'center',
    marginTop: 10,
  },
  subTitle: {
    fontFamily: 'Poppins-Bold',
    fontSize: 17,
    color: '#000',
  },
  textDesc: {
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    color: '#000',
  },
  delivery: {
    marginTop: 30,
  },
  descContent: {
    marginTop: 30,
  },
  button: {
    paddingHorizontal: 50,
    height: 70,
    borderRadius: 20,
    backgroundColor: '#6A4029',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40,
  },
  textBtn: {
    fontFamily: 'Poppins-Bold',
    fontSize: 17,
    color: '#fff',
  },
  wrapperBtnSize: {
    marginTop: 30,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  btnSize: {
    width: 60,
    height: 60,
    backgroundColor: '#FFBA33',
    borderRadius: 200,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textBtnSize: {
    fontFamily: 'Poppins-Bold',
    fontSize: 14,
  },

  iconTrash: {
    width: 40,
    height: 40,
    borderRadius: 200,
    backgroundColor: '#6A4029',
    justifyContent: 'center',
    alignItems: 'center',
  },
  wrapperPencil: {
    width: 40,
    height: 40,
    borderRadius: 150,
    backgroundColor: '#6A4029',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -30,
    marginLeft: 150,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    // alignItems: "center",
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  radio: {
    display: 'flex',
    flexDirection: 'row',
    marginRight: 20,
    alignItems: 'center',
    marginVertical: 30,
  },
  checkedOuter: {
    width: 20,
    height: 20,
    borderColor: '#6A4029',
    borderWidth: 2,
    borderRadius: 100,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  checkedInner: {
    backgroundColor: '#6A4029',
    width: 10,
    height: 10,
    borderRadius: 50,
  },
  unchekedOuter: {
    width: 20,
    height: 20,
    borderColor: '#9F9F9F',
    borderWidth: 2,
    borderRadius: 100,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkedText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    color: 'black',
    marginLeft: 15,
    paddingTop: 3.5,
  },
  uncheckedText: {
    fontFamily: 'Poppins-Bold',
    fontSize: 15,
    color: '#9F9F9F',
    marginLeft: 15,
    paddingTop: 3.5,
  },
});

export default styles;
