import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  all_container: {
    marginLeft: '10%',
    width: '80%',
    marginTop: '20%',
  },
  container_up: {
    alignItems: 'center',
  },
  input: {
    borderBottomWidth: 1,
    borderColor: '#BCBABA',
    borderWidth: 0,
    fontFamily: 'Poppins',
    fontSize: 10,
    height: 40,
    margin: 12,
    outlineWidth: 4,
    padding: 10,
    width: '80%',
    color: 'black',
    textAlign: 'center',
    fontWeight: '400',
  },
  input_bottom: {
    borderBottomWidth: 1,
    borderColor: '#BCBABA',
    borderWidth: 0,
    fontFamily: 'Poppins',
    fontSize: 14,
    height: 40,
    marginTop: 10,
    marginBottom: 10,
    outlineWidth: 4,
    // padding: 10,
    width: '90%',
    color: 'black',
    fontWeight: '400',
  },
  text: {
    color: 'black',
    fontFamily: 'Poppins',
    fontSize: 17,
    fontWeight: '900',
  },
  image: {
    borderRadius: 200,
    width: 150,
    height: 150,
    marginTop: 10,
  },

  tanggal: {
    marginVertical: 10,
    color: 'black',
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
  },
  berubah: {
    marginVertical: 10,
    color: 'black',
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
  },
  inputDate: {
    marginTop: 20,
    borderBottomColor: '#9F9F9F',
    borderBottomWidth: 1,
    marginBottom: 20,
  },
  btnSave: {
    alignItems: 'center',
    backgroundColor: '#6A4029',
    padding: 20,
    borderRadius: 20,
    justifyContent: 'center',
    marginTop: 40,
    marginBottom: 20,
  },
  textBtnSave: {
    color: '#fff',
    fontFamily: 'Poppins-Bold',
    fontSize: 17,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 50,
    paddingTop: 40,
    paddingBottom: 10,
  },
  textHeader: {
    fontFamily: 'Poppins-Bold',
    fontSize: 18,
    color: '#000',
    textAlign: 'center',
  },
  iconTrash: {
    width: 40,
    height: 40,
    borderRadius: 200,
    backgroundColor: '#6A4029',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default styles;
