import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F8',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 50,
    paddingTop: 40,
    paddingBottom: 10,
  },
  textHeader: {
    fontFamily: 'Poppins-Bold',
    fontSize: 18,
    color: '#000',
    textAlign: 'center',
  },
  iconTrash: {
    width: 40,
    height: 40,
    borderRadius: 200,
    backgroundColor: '#6A4029',
    justifyContent: 'center',
    alignItems: 'center',
  },
  all_container: {
    marginLeft: '10%',
    width: '80%',
    marginTop: '10%',
  },
  container_up: {
    alignItems: 'center',
    marginBottom: 30,
  },
  input: {
    borderBottomWidth: 1,
    borderColor: '#BCBABA',
    borderWidth: 0,
    fontFamily: 'Poppins',
    fontSize: 10,
    height: 40,
    margin: 12,
    outlineWidth: 4,
    padding: 10,
    width: '80%',
    color: 'black',
    textAlign: 'center',
    fontWeight: '400',
  },
  input_bottom: {
    borderBottomWidth: 1,
    borderColor: '#BCBABA',
    borderWidth: 0,
    fontFamily: 'Poppins',
    fontSize: 16,
    height: 40,
    marginTop: 10,
    marginBottom: 10,
    outlineWidth: 4,
    padding: 10,
    width: '90%',
    color: 'black',
    fontWeight: '400',
  },
  text: {
    color: 'black',
    fontFamily: 'Poppins',
    fontSize: 17,
    fontWeight: '900',
  },
  image: {
    borderRadius: 200,
    width: 150,
    height: 150,
    padding: 100,
    marginTop: 10,
  },
  wrapperPencil: {
    width: 40,
    height: 40,
    borderRadius: 150,
    backgroundColor: '#6A4029',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -40,
    marginLeft: 120,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    // alignItems: "center",
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    paddingHorizontal: 50,
    height: 70,
    borderRadius: 20,
    backgroundColor: '#6A4029',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 40,
  },
  textBtn: {
    fontFamily: 'Poppins-Bold',
    fontSize: 17,
    color: '#fff',
  },
  radio: {
    display: 'flex',
    flexDirection: 'row',
    marginRight: 20,
    alignItems: 'center',
    marginVertical: 30,
  },
  checkedOuter: {
    width: 20,
    height: 20,
    borderColor: '#6A4029',
    borderWidth: 2,
    borderRadius: 100,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  checkedInner: {
    backgroundColor: '#6A4029',
    width: 10,
    height: 10,
    borderRadius: 50,
  },
  unchekedOuter: {
    width: 20,
    height: 20,
    borderColor: '#9F9F9F',
    borderWidth: 2,
    borderRadius: 100,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkedText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    color: 'black',
    marginLeft: 15,
    paddingTop: 3.5,
  },
  uncheckedText: {
    fontFamily: 'Poppins-Bold',
    fontSize: 15,
    color: '#9F9F9F',
    marginLeft: 15,
    paddingTop: 3.5,
  },
});

export default styles;
