import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 50,
    paddingTop: 40,
    paddingBottom: 10,
  },
  textHeader: {
    fontFamily: 'Poppins-Bold',
    fontSize: 18,
    color: '#000',
    textAlign: 'center',
  },
  title: {
    fontFamily: 'Poppins-ExtraBold',
    fontSize: 34,
    color: '#000',
  },
  wrapperAddress: {
    marginTop: 30,
  },
  cardAddress: {
    height: 160,
    backgroundColor: '#fff',
    borderRadius: 20,
    marginTop: 10,
    paddingTop: 15,
    paddingHorizontal: 20,
    shadowColor: '#000',
    elevation: 1,
  },
  input: {
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    color: '#000',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.3)',
    paddingBottom: 3,
  },
  input2: {
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    color: '#000',
    paddingBottom: 3,
  },
  cardDeliveryMethods: {
    height: 200,
    backgroundColor: '#fff',
    borderRadius: 20,
    marginTop: 10,
    paddingTop: 15,
    paddingHorizontal: 20,
    shadowColor: '#000',
    elevation: 1,
  },
  wrapperBtnDelivery: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  btnDelivery: {
    width: 85,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#BABABA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  wrapperSetTime: {
    flexDirection: 'row',
    marginTop: 20,
    alignItems: 'center',
  },
  wrapperbtnSetTime: {
    flexDirection: 'row',
  },
  textNow: {
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    marginRight: 30,
    color: '#000',
  },
  btnSetTime: {
    width: 85,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#BABABA',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  wrapperResevation: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
  },
  textSetTime: {
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    marginRight: 5,
    color: '#000',
  },
  inputReservation: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    width: 210,
    height: 40,
    borderColor: '#BABABA',
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 10,
  },
  wrapperCost: {
    height: 65,
    backgroundColor: '#fff',
    shadowColor: '#000',
    elevation: 1,
    borderRadius: 20,
    marginTop: 40,
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textCost: {
    fontFamily: 'Poppins-Bold',
    fontSize: 20,
    color: '#000',
  },
  btnConfirm: {
    height: 65,
    backgroundColor: '#6A4029',
    shadowColor: '#000',
    elevation: 1,
    borderRadius: 20,
    marginTop: 20,
    marginBottom: 40,
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textConfirm: {
    fontFamily: 'Poppins-Bold',
    fontSize: 20,
    color: '#fff',
  },
});

export default styles;
