import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 30,
    paddingTop: 40,
    paddingBottom: 10,
  },
  textHeader: {
    fontFamily: 'Poppins-Bold',
    fontSize: 18,
    color: '#000',
    textAlign: 'center',
  },
  wrapperSearch: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 30,
    borderRadius: 30,
    backgroundColor: '#EFEEEE',
    elevation: 1,
    shadowColor: '#393939',
  },
  iconSearch: {
    color: '#000',
    fontSize: 20,
    marginRight: 10,
  },
  textPlaceholder: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 17,
    flex: 1,
  },
  sectionMenu: {
    marginVertical: 30,
  },
  grey: {
    fontFamily: 'Poppins-Regular',
    fontSize: 17,
    color: '#9A9A9D',
    marginRight: 29,
  },
  brown: {
    fontFamily: 'Poppins-Bold',
    textDecorationLine: 'underline',
    fontSize: 17,
    color: '#6A4029',
    marginRight: 29,
  },
  wrapperCard: {
    marginBottom: 10,
    marginRight: 10,
    flex: 2,
  },
  card: {
    width: 156,
    height: 212,
    backgroundColor: '#fff',
    elevation: 1,
    shadowColor: '#393939',
    borderRadius: 30,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: 55,
  },
  image: {
    width: 129,
    height: 129,
    borderRadius: 200,
    resizeMode: 'stretch',
  },
  wrapperImage: {
    width: 129,
    height: 129,
    borderRadius: 200,
    backgroundColor: '#fff',
  },
  wrapperProduct: {
    width: 150,
    alignItems: 'center',
    paddingBottom: 10,
    marginTop: 20,
    paddingHorizontal: 3,
  },
  productName: {
    height: 50,
    fontFamily: 'Poppins-ExtraBold',
    fontSize: 22,
    color: '#000',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    textAlign: 'center',
    lineHeight: 26,
  },
  productPrice: {
    fontFamily: 'Poppins-Bold',
    fontSize: 17,
    color: '#6A4029',
    marginTop: 8,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  radio: {
    flexDirection: 'row',
    marginRight: 20,
    alignItems: 'center',
    marginBottom: 20,
  },
  checkedOuter: {
    width: 20,
    height: 20,
    borderColor: '#6A4029',
    borderWidth: 2,
    borderRadius: 100,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkedInner: {
    backgroundColor: '#6A4029',
    width: 10,
    height: 10,
    borderRadius: 50,
  },
  unchekedOuter: {
    width: 20,
    height: 20,
    borderColor: '#9F9F9F',
    borderWidth: 2,
    borderRadius: 100,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  unchekedInner: {
    backgroundColor: '#9F9F9F',
    width: 15,
    height: 15,
    borderRadius: 50,
  },
  checkedText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
    color: 'black',
    marginLeft: 15,
    paddingTop: 3.5,
  },
  uncheckedText: {
    fontFamily: 'Poppins-Bold',
    fontSize: 13,
    color: '#9F9F9F',
    marginLeft: 15,
    paddingTop: 3.5,
  },
});

export default styles;
